proiect/aplicatie1/urls.py
from django.urls import path

from aplicatie1 import views

app_name = 'aplicatie1'

urlpatterns = [
    path('', views.HomeIndex.as_view(), name="home"),
    path('add_location/', views.CreateIndexView.as_view(), name="adaugare"),
    path('<int:pk>/edit_location/', views.UpdateLocationView.as_view(), name="modificare"),
]

proiect/aplicatie2/urls.py
from django.urls import path

from aplicatie2 import views

app_name = 'aplicatie2'

urlpatterns = [
    path('', views.HomeIndex.as_view(), name="home"),
    path('add_companies/', views.CreateCompaniesView.as_view(), name="adaugare"),
    path('edit_companies/<int:pk>/', views.UpdateCompaniesView.as_view(), name="modificare"),
]

proiect/proiect/urls.py
from django.contrib import admin
from django.contrib.auth.views import LoginView
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('location/', include('aplicatie1.urls')),
    path('companies/', include('aplicatie2.urls')),
    path('userprofile/', include('userprofile.urls')),
    path('', include('django.contrib.auth.urls'), {'next_page': '/'}, name='login'),
    path('', LoginView.as_view(template_name='registration/login.html'), name='login'),
]

proiect/userprofile/urls.py
from django.urls import path

from userprofile import views

app_name = 'userprofile'

urlpatterns = [
    path('updateprofile/<int:pk>/', views.UpdateProfile.as_view(), name='update_profile'),
    path('stop_pontaj/<int:pk>/', views.stopPontaj, name='stop'),
    path('new_account/', views.CreateNewUser.as_view(), name='new_account'),
    path('new_pontaj/', views.newPontaj, name='pontaj'),

]

proiect/templates/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    {% load static %}
    <meta charset="UTF-8">
    <title>Title</title>
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css"
          integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">
    <link href="{% static 'css/style.css' %}" rel="stylesheet">
</head>
<body class="about-us">
<nav class="navbar navbar-expand-lg fixed-top navbar-transparent nav-down" color-on-scroll="200">
    <div class="container">
        <div class="navbar-translate">
            <div class="navbar-header">

            </div>
            <button class="navbar-toggler navbar-burger" type="button" data-toggle="collapse"
                    data-target="#navbarToggler" aria-controls="navbarTogglerDemo02" aria-expanded="false"
                    aria-label="Toggle navigation">
                <span class="navbar-toggler-bar"></span>
                <span class="navbar-toggler-bar"></span>
                <span class="navbar-toggler-bar"></span>
            </button>
        </div>
        <div class="collapse navbar-collapse">
            <ul class="navbar-nav ml-auto">
                {% if request.user.is_authenticated %}
                {% if ready_to_work %}
                <li class="nav-item">
                    <a class="nav-link" href="{% url 'userprofile:pontaj' %}">
                        Pontaj Nou

                    </a>
                </li>
                {% else %}
                <li class="nav-item">
                    <a class="nav-link" href="{% url 'userprofile:stop' request.user.id %}">
                        Ai pontat deja
                    </a>
                </li>
                {% endif %}
                {% endif %}
                <li class="nav-item">
                    <a href="{% url 'aplicatie1:home' %}" class="nav-link" style="color:black">
                        Location
                    </a>
                </li>
                <li class="nav-item">
                    <a href="{% url 'aplicatie2:home' %}" class="nav-link" style="color:black">
                        Companies {{ customer_name }}
                    </a>
                </li>

                {% if request.user.is_authenticated %}
                    <li class="nav-item">
                        <a href="{% url 'userprofile:update_profile' request.user.id %}" class="nav-link"
                           style="color: black">{{ request.user.first_name }} {{ request.user.last_name }}</a>
                    </li>
                {% endif %}
                {% if request.user.is_authenticated == False %}
                    <li class="nav-item">
                        <a href="{% url 'login' %}" class="nav-link">
                            Login
                        </a>
                    </li>
                {% endif %}
                <li class="nav-item">
                    <a href="{% url 'userprofile:new_account' %}" class="nav-link">
                        Sign Up
                    </a>
                </li>
                {% if request.user.is_authenticated == True %}
                    <li class="nav-item">
                        <a href="{% url 'logout' %}" class="nav-link">
                            Logout
                        </a>
                    </li>
                {% endif %}
            </ul>
        </div>
    </div>
</nav>
<div class="page-header page-header-small">
    <div class="filter filter-danger"></div>
    <div class="content-center">
        <div class="container">
            {% block content %}
            {% endblock %}
        </div>
    </div>
</div>
</body>
</html>